---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "macproxy_classic"
    my_file: "install_macproxy_classic"
    module_name: "macproxy_classic"

    packages:
      - python3
      - python3-venv
      - python3-pip

    service_name: "macproxy"

    templates:
      - { name: "{{ service_name }}.service", dest: "/etc/systemd/system" }

    repo: https://github.com/rdmark/macproxy_classic.git

    firewalld_ports:
      - { port: 5001, protocol: tcp }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.import_role:
        name: retronas.role.package.latest

    - name: "{{ my_name }} - clone repo"
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: /opt/{{ my_name }}

    - ansible.builtin.import_role:
        name: retronas.role.templates

    - ansible.builtin.import_role:
        name: retronas.role.firewalld.port

    - ansible.builtin.import_role:
        name: retronas.role.system-config

  handlers:
    - name: "{{ my_name }} Restart Services"
      ansible.builtin.service:
        name: "{{ service_name }}.service"
        state: started
        enabled: true
        daemon_reload: true
